{% set name = "libcdms" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/CDAT/libcdms/archive/v3.1.0.tar.gz
  sha256: 887107ef1a48e057065ee1c01e0ae1ea1b430e8ce9e2d722686b1e82e9dbb473

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - hdf5
    - libnetcdf
    - jasper
    - g2clib
    - libpng
    - libtiff
    - jpeg
    - libdrs
  run:
    - hdf5
    - libnetcdf
    - jasper
    - g2clib
    - libpng
    - libtiff
    - jpeg
    - libdrs

test:
  commands:
    - test -f $PREFIX/lib/libcdms.a

about:
  home: https://github.com/CDAT/libcdms
  license: '3-Clause BSD'
  license_file: 'bsd-3-clause.txt'
  summary: 'Climate Data Management System library'
  description: |
      The Climate Data Management System is an object-oriented data
      management system, specialized for organizing multidimensional,
      gridded data used in climate analysis and simulation.
  dev_url: https://github.com/CDAT/libcdms

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
